version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django-dev
    restart: unless-stopped

  # client:
  #   build:
  #     context: ./client/
  #   command: npm start
  #   restart: always
  #   volumes:
  #     - ./client:/home/app
  #     - /home/app/node_modules
  #   ports:
  #     - 8001:8001

  # web:
  #   build: .
  #   command: python manage.py runserver 0.0.0.0:8000
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: django-dev
  #     HOST: db
  #     PORT: 5432
  #   restart: unless-stopped
  #   volumes:
  #     - .:/code
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   links:
  #     - db