# Generated by Django 2.2 on 2019-04-20 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakedetailchild',
            name='product_detail',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fake_child', to='product.ProductDetailModel'),
        ),
        migrations.AlterField(
            model_name='productdetailmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='product.ProductModel'),
        ),
    ]
