# Generated by Django 2.2 on 2019-05-12 14:49

from django.db import migrations
import django.utils.timezone
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190420_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='images',
            field=versatileimagefield.fields.VersatileImageField(default=django.utils.timezone.now, upload_to='images/', verbose_name='ProductImages'),
            preserve_default=False,
        ),
    ]
