# Generated by Django 2.2 on 2019-05-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productmodel_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='images',
        ),
    ]
