# Generated by Django 2.2 on 2019-06-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_productmodel_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(default='default_value', max_length=100)),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='images')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.RemoveField(
            model_name='productdetailmodel',
            name='product',
        ),
        migrations.DeleteModel(
            name='FakeDetailChild',
        ),
        migrations.DeleteModel(
            name='ProductDetailModel',
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
