# Generated by Django 2.2.2 on 2019-06-30 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20190630_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categori',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.Category'),
        ),
        migrations.AlterField(
            model_name='car',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to=settings.AUTH_USER_MODEL),
        ),
    ]
