# Generated by Django 2.2.2 on 2019-06-30 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20190630_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='categori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.Category'),
        ),
    ]
