# Generated by Django 2.2.2 on 2019-07-01 08:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20190701_0603'),
    ]

    operations = [
        migrations.AddField(
            model_name='carscategory',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 1, 8, 40, 18, 887420, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='carscategory',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
