# Generated by Django 2.2.2 on 2019-07-01 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20190701_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
