# Generated by Django 2.2.2 on 2019-07-01 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_auto_20190701_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ['-created_date']},
        ),
        migrations.AddField(
            model_name='car',
            name='description_en',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(1)]),
        ),
        migrations.AddField(
            model_name='car',
            name='description_ge',
            field=models.TextField(default='', validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
