# Generated by Django 2.2.2 on 2019-07-07 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_auto_20190701_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarHas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heating', models.BooleanField(default=False)),
                ('microphone', models.BooleanField(default=False)),
                ('additional_boot', models.BooleanField(default=False)),
                ('bicycle_clip', models.BooleanField(default=False)),
                ('air_conditioner', models.BooleanField(default=False)),
                ('mini_bar', models.BooleanField(default=False)),
                ('child_seat', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('ski_clip', models.BooleanField(default=False)),
                ('navigation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CarsManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='car',
            name='additional_boot',
        ),
        migrations.RemoveField(
            model_name='car',
            name='air_conditioner',
        ),
        migrations.RemoveField(
            model_name='car',
            name='bicycle_clip',
        ),
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.RemoveField(
            model_name='car',
            name='child_seat',
        ),
        migrations.RemoveField(
            model_name='car',
            name='heating',
        ),
        migrations.RemoveField(
            model_name='car',
            name='microphone',
        ),
        migrations.RemoveField(
            model_name='car',
            name='mini_bar',
        ),
        migrations.RemoveField(
            model_name='car',
            name='navigation',
        ),
        migrations.RemoveField(
            model_name='car',
            name='refrigerator',
        ),
        migrations.RemoveField(
            model_name='car',
            name='ski_clip',
        ),
        migrations.RemoveField(
            model_name='car',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='car',
            name='wifi',
        ),
        migrations.CreateModel(
            name='CarEditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.CarsCategory')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.CarsManufacturer')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='additional_information',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.CarEditionalInformation'),
        ),
        migrations.AddField(
            model_name='car',
            name='has',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.CarHas'),
        ),
    ]
