# Generated by Django 2.2 on 2019-07-18 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_auto_20190707_0955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'ordering': ('-created_date',)},
        ),
    ]
