# Generated by Django 2.2 on 2019-07-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0015_auto_20190718_1156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarAdditionalInformation',
            new_name='AdditionalInformation',
        ),
        migrations.RenameModel(
            old_name='CarsManufacturers',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='CarHas',
            new_name='Has',
        ),
        migrations.RenameModel(
            old_name='CarsCategories',
            new_name='Manufacturers',
        ),
    ]
