# Generated by Django 2.2 on 2019-07-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0016_auto_20190719_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.Categories'),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='cars.Manufacturers'),
        ),
    ]
